name: Reuse other workflow

on:
  workflow_dispatch:
    inputs:
      main_param_1:
        description: 'Type any old stuff!'
        type: string
        required: true      
        
jobs:
  call-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      who-to-greet: ${{ inputs.main_param_1 }}'

  use-output:
    runs-on: ubuntu-latest
    needs: [call-workflow]
    steps:
      - run: echo "Time was ${{ needs.call-workflow.outputs.current-time }}"      
